### ISSUE TITLE
Repository size field does not support long values.

### ISSUE THREAD

**Issue by stil4m** [hkarthik7/azure-devops-java-sdk#13]
If retrieving repositories with where the size of the repository is rather large, then the JSON object mapping fails with the following exception:

```
Exception in thread "main" org.azd.exceptions.AzDException: ApiResponseParsingException: Numeric value (39027429139) out of range of int (-2147483648 - 2147483647)
 at [Source: (StringReader); line: 1, column: 261214] (through reference chain: org.azd.git.types.Repositories["value"]->java.util.ArrayList[270]->org.azd.git.types.Repository["size"])
```

Steps to reproduce
------------------

Run the following Java code:

```java
public class Example {

    public static void main(String[] args) throws AzDException {
        var organisation = "<my org>";
        var personalAccessToken = "<access code>";
        var webApi = new AzDClientApi(organisation, personalAccessToken);
        var core = webApi.getCoreApi();
        System.out.println(webApi.getGitApi().getRepositories());
    }
}

```

Have a large Git repository. For example the following JSON response on the repositories API:

```
{
  "value": [
    ...
    {
      "id": "<private>",
      "name": "<private>",
      "url": "<private>",
      "project": {
        ...
      },
      "size": 39027429139,
      ...
    }
    ...
  ]
}

```

Expected behavior
-----------------

```none
Status code 0
```

Actual behavior
---------------

```none
Exception was raised by `JsonMapper`
```

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields
otherwise the issue template will be treated as an incomplete report.

- [x] Bug Description Added
- [x] Reproduce Steps Added
- [x] Expected Behaviour Added
- [x] Actual Behaviour Added

**Comment by hkarthik7** [comment]
@stil4m thanks for pointing this out and for the [PR](https://github.com/hkarthik7/azure-devops-java-sdk/pull/14).
