### ISSUE TITLE
browsing repository content

### ISSUE THREAD

**Issue by vincent-fuchs** [hkarthik7/azure-devops-java-sdk#15]
Hi,

I had a look at the documentation, but I am not finding anything, so I just want to ask the question in case I missed something : the API mentions that we can browse a repository content (see https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-file-contents?view=azure-devops-rest-6.0 ), but that feature is not there (yet ?) in the SDK, right ? 

thanks

**Comment by hkarthik7** [comment]
Hello @vincent-fuchs, Thanks for highlighting this. You’re right, repository browsing feature is not there in SDK. Feel free to add it and create a pull request, happy to merge it. Or it will be included in next release.
