### ISSUE TITLE
Pipelines API not working

### ISSUE THREAD

**Issue by elmer** [hkarthik7/azure-devops-java-sdk#18]
Steps to reproduce
------------------

```java
    @Test
    void pipelineTest() {
    
    
        AzDClientApi client = new AzDClientApi(devOpsConfig.getOrganization(),devOpsConfig.getPat());

        PipelinesApi pipelinesApi = client.getPipelinesApi();
        
        try {
            pipelinesApi.getPipelines().getPipelines().forEach(pipeline -> {
                System.out.println(pipeline.getId());
            });

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

```

Result:
```text
org.azd.exceptions.AzDException: ApiResponseParsingException: Unrecognized token 'Page': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Page not found."; line: 1, column: 5]                                                                                                                                                           
        at org.azd.helpers.JsonMapper.mapJsonResponse(JsonMapper.java:47) 

```

**Comment by hkarthik7** [comment]
Hello @elmer,

I could see that ‘project name’ is missing in the client API connection declaration. Pipelines API requires project name - https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/pipelines/list?view=azure-devops-rest-7.1 .

Please try like this:

    @Test
    void pipelineTest() {
    
    
        AzDClientApi client = new AzDClientApi(devOpsConfig.getOrganization(), devOpsConfig.getProject, devOpsConfig.getPat());

        PipelinesApi pipelinesApi = client.getPipelinesApi();
        
        try {
            pipelinesApi.getPipelines().getPipelines().forEach(pipeline -> {
                System.out.println(pipeline.getId());
            });

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

Example here - https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/examples/PipelinesApi.md

Documentation - 
https://azure-devops-java-sdk-docs.readthedocs.io/en/latest/docs/pipelines/

Cheers.

**Comment by elmer** [comment]
Ugh, missed that parameter. Thank you.
