### ISSUE TITLE
Support Attachments for Work Items

### ISSUE THREAD

**Issue by wiifitresort** [hkarthik7/azure-devops-java-sdk#19]
Currently SDK doesn't support adding attachments to work items.  Please add support for attachments.

Steps to reproduce
------------------

```java

```

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields
otherwise the issue template will be treated as an incomplete report.

- [X] Bug Description Added
- [X] Reproduce Steps Added
- [X] Expected Behaviour Added
- [X] Actual Behaviour Added

**Comment by hkarthik7** [comment]
Hello @wiifitresort, thanks for raising, this will be addressed in next version release.
