### ISSUE TITLE
feature enhancement - project feature toggle - unpublished API

### ISSUE THREAD

**Issue by gabechan** [hkarthik7/azure-devops-java-sdk#33]
Please see the following blog post and community discussion link:
* https://www.teapotcoder.com/post/vsts-disable-features-services-api/
* https://developercommunity.visualstudio.com/t/manage-azure-devops-services-using-rest-api/905506

This is to programmatically enable / disable project services such as `Boards`, `Test Plans`, etc. (see screenshot)

I've confirmed the functionality currently still works.

I'm planning to add this functionality to my app. Since this is not an official published API feature, I'm just confirming if you want me to add this to this library.
If not, I will implement outside, either in my calling app or in my fork only.

![Screen Shot 2022-06-27 at 3 07 50 PM](https://user-images.githubusercontent.com/1183750/176045146-b95d6cd4-f7a4-4385-9e30-ce779f982cd2.png).

**Comment by hkarthik7** [comment]
Hi @gabechan, Thanks for asking, please go ahead and implement the feature. The method **getOrganizations()** in **AccountsApi** is not a direct API listed in documentation, it was implemented as we needed it.
