### ISSUE TITLE
VariableGroupProviderData is missing lastRefreshedOn field

### ISSUE THREAD

**Issue by nbihan-mediware** [hkarthik7/azure-devops-java-sdk#42]
When trying to expand tasks for a release release API is throwing an exception

```java
releaseApi.getRelease(release.getId(), SingleReleaseExpands.TASKS);
```

ApiResponseParsingException: Unrecognized field "lastRefreshedOn" (class org.azd.distributedtask.types.VariableGroupProviderData), not marked as ignorable (2 known properties: "vault", "serviceEndpointId"])
 at [Source: (StringReader); line: 1, column: 290593] (through reference chain: org.azd.release.types.Release["variableGroups"]->java.util.ArrayList[1]->org.azd.release.types.VariableGroup["providerData"]->org.azd.distributedtask.types.VariableGroupProviderData["lastRefreshedOn"])

It's because this is missing the field described in AzureKeyVaultVariableGroupProviderData interface
https://github.com/microsoft/azure-devops-node-api/blob/9ccac86e5bb38c553c433b4e300d920e7e3e2b40/api/interfaces/ReleaseInterfaces.ts#L535

**Comment by hkarthik7** [comment]
@nbihan-mediware I'm sorry that you're facing this issue. Actually, we rely on Azure DevOps documentation and response from API to form the types and definitions for the library. I couldn't find this in the documentation hence I missed it. Please feel free to raise a PR and I'm happy to merge it. Here is the [VariableGroupProviderData](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/distributedtask/types/VariableGroupProviderData.java) file.

**Comment by nbihan-mediware** [comment]
@hkarthik7 I raised a PR
https://github.com/hkarthik7/azure-devops-java-sdk/pull/45
Can you please look into it?

**Comment by hkarthik7** [comment]
Hiya @nbihan-mediware, sure will do. Pretty busy this week, you expect a release next week or so.

**Comment by hkarthik7** [comment]
@nbihan-mediware closing this issue as the PR is merged and a version is released.
