### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by SatriaPriambada** [hkarthik7/azure-devops-java-sdk#43]
Hi Karthik,
Thanks for the hard work!
I think this is a great azure devops java library 
I was wondering if there'll be support for Android?

Have a nice day!

**Comment by hkarthik7** [comment]
Hey @SatriaPriambada mate, apologies, currently there is no support for android. I don't have any plans now to add support for android.

**Comment by SatriaPriambada** [comment]
Ok thanks for the info. I'm closing the issue
