### ISSUE TITLE
How to authenticate with REST API via OAuth

### ISSUE THREAD

**Issue by champlin2** [hkarthik7/azure-devops-java-sdk#46]
Most of the examples have the code authenticating with Azure via a PAT (Personal Access Token) but the application I'm writing runs as a background agent and syncs Azure with another system.  I saw in the Connection class there is a way to pass the AuthorizedToken object to get an OAuth connection but I wasn't 100% sure if I had the steps correct (starting with OAuthApi.getAuthorizationEndpoint?).

Do you have a Java sample of how to connect via OAuth you could post?  I currently have the tenant Id, client id and client secret of the application as defined in Azure.  Do I need other pieces of information?

**Comment by hkarthik7** [comment]
Hey @champlin2, You don't necessarily have to use PAT to authenticate the REST API. There are two ways to authenticate, one is using PAT and other is using OAuth2.0. As described in the [documentation](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops) you need to [register](https://app.vsaex.visualstudio.com/app/register) your application to get a client id, client secret, callback url. The callback url will have the jwt token.

Using client id, client secret and callaback url create a [Connection](https://hkarthik7.github.io/azd-docs/org/azd/connection/Connection.html) object. Specify [tokenRefreshedHandler](https://hkarthik7.github.io/azd-docs/org/azd/connection/Connection.TokenRefreshedHandler.html) to refresh your auth token automatically when it expires.

Please use [OAuthApi](https://hkarthik7.github.io/azd-docs/org/azd/oauth/OAuthApi.html) first to get the authorization endpoint and access token. OAuthApi has static methods,

- getAuthorizationEndpoint
- getAccessToken
- getRefreshToken
- hasTokenExpired (helper method to check if the token has expired)

OAuthApi injects the timestamp when a new access token is generated and you can use `hasTokenExpired` to check and get the refresh token.

Once you have the access token, you can then create a connection object with that and call other Apis.

**Comment by hkarthik7** [comment]
Hiya @champlin2, Please let me know if your issue is solved or you need any help. This issue will be closed after few days.

**Comment by champlin2** [comment]
Thanks again for your help. I think you can close the issue. I’ve got the
basics in place for the agent but got pulled to work on something different
at the moment. I’ll touch base when I get back to it and let you know how
it goes

**Comment by hkarthik7** [comment]
Cheers, good luck.
