### ISSUE TITLE
Json mapping issue when trying to read builds that couldn't run

### ISSUE THREAD

**Issue by elhoo** [hkarthik7/azure-devops-java-sdk#48]
# Issue Template
Hi,

We get this error:
org.azd.exceptions.AzDException: ApiResponseParsingException: Cannot construct instance of `org.azd.build.types.ValidationResult` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('error')
 at [Source: (StringReader); line: 1, column: 5734] (through reference chain: org.azd.build.types.Builds["value"]->java.util.ArrayList[1]->org.azd.build.types.Build["validationResults"]->java.util.ArrayList[0]->org.azd.build.types.BuildRequestValidationResult["result"])
	at org.azd.helpers.JsonMapper.mapJsonResponse(JsonMapper.java:49) ~[azd-5.0.4.jar:?]

When trying to get builds. This occurs when we have a pipeline run that failed to start (by errors in yaml syntax or, in this case service account suspended).

![image](https://user-images.githubusercontent.com/1180446/201348401-82681dab-d578-48b0-b55e-958264061835.png)

![image](https://user-images.githubusercontent.com/1180446/201348635-dd94a25f-1cc2-4ec2-9e3d-950d70afe666.png)

Response from azure devops:
```json
      "validationResults": [
        {
          "result": "error",
          "message": "The pipeline is not valid. Could not get the latest source version for repository XXXX hosted on https://github.com/ using ref refs/tags/v3. GitHub reported the error, \"Sorry. Your account was suspended.\""
        }
      ],
```

- You should provide a description for the bug
- Add exception message and stacktrace if available
- Please attach screen captures if available
- Additionally, you can specify your OS version, IDE you are using and the SDK version

Steps to reproduce
------------------
Run a pipeline with invalid yaml or service account disabled.

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise the
issue template will be treated as an incomplete report.

- [ ] Bug Description Added
- [ ] Reproduce Steps Added
- [ ] Expected Behaviour Added
- [ ] Actual Behaviour Added

**Comment by hkarthik7** [comment]
Hiya @elhoo, I'm sorry that you're facing this issue, **ValidationResult** should be an `enum` and not a `class`. I will fix it and push the changes.

**Comment by hkarthik7** [comment]
Hi @elhoo, New version is released with the fix. I'm leaving the defect open and monitor for feedback.

**Comment by elhoo** [comment]
Thanks,
I think it fixed it... now I'm facing another problem related to the topic ..

If a pipeline run fails with 
> There was a resource authorization issue: "The pipeline is not valid. Could not find a pool with name XXXXX. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz. Could not find a pool with name XXXXXX. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Then I get:
```
Exception occurred when processing los-sandbox
org.azd.exceptions.AzDException: ApiResponseParsingException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at org.azd.helpers.JsonMapper.mapJsonResponse(JsonMapper.java:49) ~[azd-5.0.5.jar:?]
	at org.azd.build.BuildApi.getTimeline(BuildApi.java:1472) ~[azd-5.0.5.jar:?]
```

**Comment by hkarthik7** [comment]
@elhoo, sure let me take a look. From the look, Build Timeline API response is not deserialised properly. I will check the properties of Timeline API.

**Comment by hkarthik7** [comment]
@elhoo, which method are you calling from `BuildApi`? Is it `restoreWebhooks`?

**Comment by hkarthik7** [comment]
@elhoo, I'm closing this issue now as new version `5.0.6` is released. Hope that should fix the issue.
