### ISSUE TITLE
Documentation of RestClient or Unit tests of RestClient needed

### ISSUE THREAD

**Issue by djangofan** [hkarthik7/azure-devops-java-sdk#49]
# Issue Template

Can you add unit tests for org.azd.utils.RestClient class so that I know how it works?

If you had unit tests, hitting a site such as JsonPlaceholder, then I would know how to use the client.

Steps to reproduce
------------------

Basically  I have a need to query the  test/runs endpoint so I can get test result information for builds.   Your API does not seem to support that endpoint, documented here: https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/list?view=azure-devops-rest-7.0&tabs=HTTP

curl --location --request GET 'https://dev.azure.com/Company/MyTeam/_apis/test/runs?api-version=7.0&includeRunDetails=true&project=MyTeam'

If you don't have any good examples of using your rest client, or any documentation, **then I will be forced to use a different 3rd party library**.  I wanted to keep it simple and use yours, if possible.    The arguments that the send methods take are cryptic.

Expected behavior
-----------------

```none

```

Actual behavior
---------------

```none

```

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise the
issue template will be treated as an incomplete report.

- [ ] Bug Description Added
- [ ] Reproduce Steps Added
- [ ] Expected Behaviour Added
- [ ] Actual Behaviour Added

**Comment by djangofan** [comment]
Example that didn't work, and seems like it should have worked:
//  HTTP query to get all test runs to see if these ids are in there
            response = RestClient.send("https://dev.azure.com/Company/MyTeam/_apis/test/runs",
                    RequestMethod.GET, null, CustomHeader.JSON_CONTENT_TYPE, true);

**Comment by hkarthik7** [comment]
Hiya @djangofan, I'm sorry that you can't find any examples, I will make sure to add more detailed and step by step approach for all the APIs in the library. Just to start with please see the documentation [here](https://azure-devops-java-sdk-docs.readthedocs.io/en/latest/docs/tutorial/) that gives the overview of how to call Azure DevOps REST Api using `RestClient`.

For now, please give the code a try - 

```java
var webApi = new AzDClientApi("organisationName", "projectName", "personalAccessToken");

var response = RestClient.send(RequestMethod.GET, webApi.getConnection(), ResourceId.TEST, 
webApi.getConnection().getProject(), "test/runs", null, null, "7.0", Map.of("includeRunDetails", true), null, null);
```

**webApi** is required when calling the send method as it contains - organisation, project name and access token to call the API.

Please refer to [resource-area-identifiers.txt](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/resource-area-identifiers.txt) to know what resource id to pass as this is used by the Api to dynamically construct the URL. If there is no resource id found we can use the base URL as `https://dev.azure.com/`.  The [Instance](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/enums/Instance.java) *enum* class provides a property `BASE_INSTANCE` and you can use it to avoid hardcoding the URL base instance in your code. Additionally, some APIs demands the sub-domain, for instance [Releases](https://learn.microsoft.com/en-us/rest/api/azure/devops/release/releases/list?view=azure-devops-rest-7.0&tabs=HTTP) API, `GET https://vsrm.dev.azure.com/{organization}/{project}/_apis/release/releases?api-version=7.0`. To tackle this, either we use the resource id or call `setSubdomain` method from [Instance](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/enums/Instance.java) *enum* class to add the sub domain `vsrm` to the base URL `https://dev.azure.com` --> `https://vsrm.dev.azure.com`. One such example usecase is `uploadPackage` method in [MavenApi](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/maven/MavenApi.java#L456).

You can use [scrape.py](https://github.com/hkarthik7/azure-devops-java-sdk/tree/main/tools) from tools folder to automatically create the definition files for [Test Runs Api](https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/list?view=azure-devops-rest-7.0&tabs=HTTP).

Then you can use the created definition file to convert json string from `response` variable to **POJO**.

```java
var mapper = new JsonMapper();
mapper.mapJsonResponse(response, TestRuns.class);
```

I will add the support for **Test Api** in next version release.

Please feel free to drop a note if it worked, if it doesn't work please comment with the errors.

Cheers.

**Comment by hkarthik7** [comment]
@djangofan, I'm closing this issue for now. I've added tests and will add more tests going forward and update the documentation too. Please open a new one in case if you need any further help on this.
