### ISSUE TITLE
Possible to compile with Java 8

### ISSUE THREAD

**Issue by champlin2** [hkarthik7/azure-devops-java-sdk#51]
When building azd from the command line using Maven it requires that Java 11 or higher is used to build the jar.

The problem I'm having is I would like to use the jar as part of a script library in HCL Domino however unfortunately the latest release (Domino 12.0.2) only supports up to Java 8 so when the jar is loaded it errors out.

Is there any way the azd jar could be built with Java 8 (even if I had to lose some functionality)?  I only need the WorkItem/WorkItemTracking functionality to sync issues from a Notes-based database to Azure DevOps.

**Comment by hkarthik7** [comment]
Hiya @champlin2, it is not possible to decompile java 11 to 8. However, there is a workaround you can do with [this plugin](https://github.com/bsideup/jabel).  I haven't tested it but you can give it a try. Clone the source code and add the entries as provided in the [README](https://github.com/bsideup/jabel#jabel---use-modern-java-9-14-syntax-when-targeting-java-8) page in pom.xml file.

**Comment by champlin2** [comment]
@hkarthik7 thanks for the suggestion but after setting it up it's getting the following compile errors:

G:\git\azure-devops-java-sdk\azd>mvn package -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< io.github.hkarthik7:azd >-----------------------
[INFO] Building azd 5.0.6
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- resources:3.0.2:resources (default-resources) @ azd ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\git\azure-devops-java-sdk\azd\src\main\resources
[INFO]
[INFO] --- compiler:3.8.1:compile (default-compile) @ azd ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 599 source files to G:\git\azure-devops-java-sdk\azd\target\classes
**Jabel: initialized**
[INFO] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java: Some input fil
es use unchecked or unsafe operations.
[INFO] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java: Recompile with
 -Xlint:unchecked for details.
[INFO] Some messages have been simplified; recompile with -Xdiags:verbose to get full output
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[10,21] packag
e java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[11,21] packag
e java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClientProvider.java:[10,21
] package java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[8,21] pac
kage java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[9,21] pac
kage java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[10,21] pa
ckage java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[125,37] canno
t find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.RestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[240,24] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[241,25] packa
ge HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[229,41] canno
t find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.RestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[19,30] pa
ckage HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[20,26] ca
nnot find symbol
  symbol:   class HttpClient
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[21,26] ca
nnot find symbol
  symbol:   class HttpClient
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[41,31] pa
ckage HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[60,67] ca
nnot find symbol
  symbol:   class HttpRequest
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[60,94] pa
ckage HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[60,42] ca
nnot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[71,29] pa
ckage HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[80,52] pa
ckage HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[94,107] p
ackage HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[94,41] ca
nnot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[112,107]
package HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[113,75] p
ackage HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[112,41] c
annot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[134,108]
package HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[135,44] p
ackage HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[134,41] c
annot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[156,106]
package HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[157,42] p
ackage HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[156,41] c
annot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[173,110]
package HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[173,41] c
annot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[191,93] p
ackage HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[192,79] p
ackage HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[190,41] c
annot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[222,33] p
ackage HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[235,73] c
annot find symbol
  symbol:   class HttpRequest
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[235,100]
package HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[235,44] c
annot find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/git/GitApi.java:[15,21] package java
.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/git/GitApi.java:[16,21] package java
.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/maven/MavenApi.java:[17,21] package
java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/maven/MavenApi.java:[18,21] package
java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/wiki/WikiApi.java:[20,21] package ja
va.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/wiki/WikiApi.java:[21,21] package ja
va.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/wiki/WikiApi.java:[22,21] package ja
va.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/oauth/OAuthApi.java:[12,21] package
java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/oauth/OAuthApi.java:[13,21] package
java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/wiki/WikiApi.java:[667,39] cannot fi
nd symbol
  symbol:   class HttpHeaders
  location: class org.azd.wiki.WikiApi
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/helpers/StreamHelper.java:[10,21] pa
ckage java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/Client.java:[11,21] package ja
va.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[9,21] package
 java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[10,21] packag
e java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[11,21] packag
e java.net.http does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[27,26] cannot
 find symbol
  symbol:   class HttpClient
  location: class org.azd.utils.BaseClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[46,43] packag
e HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[59,43] packag
e HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[70,48] cannot
 find symbol
  symbol:   class HttpRequest
  location: class org.azd.utils.BaseClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[310,46] packa
ge HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[317,45] packa
ge HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[326,68] packa
ge HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[390,53] canno
t find symbol
  symbol:   class HttpResponse
  location: class org.azd.utils.BaseClient.StreamBuilder
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseClient.java:[427,36] canno
t find symbol
  symbol:   class HttpClient
  location: class org.azd.utils.BaseClient.StreamBuilder
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[19,68] pa
ckage HttpClient does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[20,46] ca
nnot find symbol
  symbol:   variable HttpClient
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[21,51] ca
nnot find symbol
  symbol:   variable HttpClient
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[43,20] ca
nnot find symbol
  symbol:   variable HttpRequest
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/BaseRestClient.java:[47,16] ca
nnot find symbol
  symbol:   variable HttpRequest
  location: class org.azd.utils.BaseRestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClientProvider.java:[46,33
] package HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClientProvider.java:[47,37
] cannot find symbol
  symbol:   variable HttpResponse
  location: class org.azd.utils.RestClientProvider
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[56,28] packag
e HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[57,29] packag
e HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[59,33] cannot
 find symbol
  symbol:   variable HttpResponse
  location: class org.azd.utils.RestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[100,28] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[101,29] packa
ge HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[102,33] canno
t find symbol
  symbol:   variable HttpResponse
  location: class org.azd.utils.RestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[146,32] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[147,33] packa
ge HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[150,28] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[151,29] packa
ge HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[174,28] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[175,29] packa
ge HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[176,33] canno
t find symbol
  symbol:   variable HttpResponse
  location: class org.azd.utils.RestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[202,36] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[203,37] packa
ge HttpResponse does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[204,33] canno
t find symbol
  symbol:   variable HttpResponse
  location: class org.azd.utils.RestClient
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[247,47] canno
t find symbol
  symbol:   method of(java.lang.String,org.azd.enums.CustomHeader)
  location: interface java.util.Map
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/utils/RestClient.java:[249,20] packa
ge HttpRequest does not exist
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/helpers/URLHelper.java:[29,53] incom
patible types: java.nio.charset.Charset cannot be converted to java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/helpers/URLHelper.java:[38,53] incom
patible types: java.nio.charset.Charset cannot be converted to java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/test/TestApi.java:[91,70] cannot fin
d symbol
  symbol:   method of(java.lang.String,int)
  location: interface java.util.Map
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/test/TestApi.java:[106,70] cannot fi
nd symbol
  symbol:   method of(java.lang.String,java.lang.String)
  location: interface java.util.Map
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[124,53] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[158,53] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[164,53] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[170,53] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[233,49] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[237,49] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[275,49] c
annot find symbol
  symbol:   method isBlank()
  location: variable x of type java.lang.String
[ERROR] /G:/git/azure-devops-java-sdk/azd/src/main/java/org/azd/security/SecurityApi.java:[286,47] c
annot find symbol
  symbol:   method of(java.lang.String,java.lang.String)
  location: interface java.util.List

**Comment by hkarthik7** [comment]
@champlin2 right, **azd** uses httpclient which was introduced in Java 11. I’m sorry that didn’t work. You might have to write your own logic with HttUrlConnection to support v8. Here is an [example](https://www.baeldung.com/java-http-request).

**Comment by hkarthik7** [comment]
Hello @champlin2, Apologies, I couldn't find anything useful that helps to solve this. You can use HttUrlConnection as mentioned in the above comment. I'm closing this issue for now.
