### ISSUE TITLE
GitRepository does not support repositories with size greater than 2147483647 bytes

### ISSUE THREAD

**Issue by Rhadamanthys79** [hkarthik7/azure-devops-java-sdk#52]
# Issue Template

I'm tring to clone a very large repository ( ~30Gb ) but I got the following error :

org.azd.exceptions.AzDException: ApiResponseParsingException: Numeric value (**30134050676**) out of range of int (-2147483648 - **2147483647**)
 at [Source: (String)"{"id":"7dc78671-3aca-4f78-adb7-06d5c183a1cb","name":"XXXX","url":"XXXX","project":{"id":"XXXXX","name":"XXXXX","description":"XXXXX","url":"XXXXX","state":"wellFormed","revision":2665,"visibility":"priva"[truncated 1531 chars]; line: 1, column: 604] (through reference chain: org.azd.git.types.GitRepository["size"])
	at org.azd.helpers.JsonMapper.mapJsonResponse(JsonMapper.java:49) ~[azd-5.0.6.jar:na]
	at org.azd.git.GitApi.getRepository(GitApi.java:135) ~[azd-5.0.6.jar:na]

Library version : **5.0.6**

This issue is the same reported here : https://github.com/hkarthik7/azure-devops-java-sdk/issues/13
Possible solution : change the type of the size field from Integer to Long in class GitRepository ( package org.azd.git.types )

Steps to reproduce
------------------
AzDClientApi azDClientApi = new AzDClientApi("xxxx", "xxxxx", "xxxxx");
GitRepository gitRepository = azDClientApi.getGitApi().getRepository("<my-repository>"); // repository size must be > 2Gb

Expected behavior
-----------------

No Exception raised and the JSON provided by Azure DevOps is correctly mapped in the GitRepository class

Actual behavior
---------------
Exception **org.azd.exceptions.AzDException: ApiResponseParsingException** raised

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise the
issue template will be treated as an incomplete report.

- [X] Bug Description Added
- [X] Reproduce Steps Added
- [X] Expected Behaviour Added
- [X] Actual Behaviour Added

**Comment by hkarthik7** [comment]
Hiya @Rhadamanthys79, please feel free open a PR happy to merge it.

**Comment by hkarthik7** [comment]
@Rhadamanthys79, thanks for the raising the PR. I've merged it, keeping this issue open for tracking purpose.
