### ISSUE TITLE
Parsing exception for ReleaseDefinition that has an an Environment that has Conditions.

### ISSUE THREAD

**Issue by kurtn718** [hkarthik7/azure-devops-java-sdk#56]
# Issue Template

A parsing exception occurs when getting a ReleaseDefinition that has an an Environment that has Conditions.   Exception below:

org.azd.exceptions.AzDException: ApiResponseParsingException: Cannot construct instance of `org.azd.release.types.ConditionType` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('event')
 at [Source: (StringReader); line: 1, column: 11013] (through reference chain: org.azd.release.types.ReleaseDefinition["environments"]->java.util.ArrayList[0]->org.azd.release.types.ReleaseDefinitionEnvironment["conditions"]->java.util.ArrayList[0]->org.azd.release.types.Condition["conditionType"])
	at org.azd.helpers.JsonMapper.mapJsonResponse(JsonMapper.java:49)
	at org.azd.release.ReleaseApi.getReleaseDefinition(ReleaseApi.java:430)

Will submit a PR for this as the fix is simple.    We should be using the corresponding enum instead of a class.

Steps to reproduce
------------------

Create a Release Definition that has an Environment that has one ore more conditions.

Expected behavior
-----------------

No exception should occur (and the Release Definition should be successfully fetched/parsed from server

Actual behavior
---------------

Exception occurs

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise the
issue template will be treated as an incomplete report.

- [x] Bug Description Added
- [x] Reproduce Steps Added
- [x] Expected Behaviour Added
- [x] Actual Behaviour Added

**Comment by hkarthik7** [comment]
Hiya @kurtn718, thanks for raising the PR. I will try to merge it today if not tomorrow.
