### ISSUE TITLE
Enhance the API to connect to on premise Azure DevOps server

### ISSUE THREAD

**Issue by lefty-kreouzis** [hkarthik7/azure-devops-java-sdk#58]
The current SDK can only connect to Azure DevOps in the cloud - looking at the code this looks like it is due to the Instance.BASE_INSTANCE value hard-coded to 'BASE_INSTANCE("https://dev.azure.com/")'

This value in-turn is used by RestClientProvider getLocationUrl(String resourceID, String organizationName)  method that is used to connect to the ADO endpoints

As the various connection APIs mainly pass the organizationName and projectName parameters and changing the signature will be cumbersome and invasive a hack could be just changing the getLocationUrl method - if the organizationName is a full url (starting with https://....) you could keep the value unchanged otherwise prepend with the BASE_INSTANCE

**Comment by hkarthik7** [comment]
Hiya @lefty-kreouzis, this is not tested with the TFS server. Please feel free to clone and test it and open a PR. Happy to merge it.

**Comment by hkarthik7** [comment]
Hi @lefty-kreouzis, I've added a method `setInstance` in [Instance](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/enums/Instance.java) `enum` to set the base instance. Now you can change the instance and call the Api. Please review it and let me know as I don't have Azure DevOps server running to test it?

**Comment by hkarthik7** [comment]
For example, 

```java
String organisation = "myOrganisationName";
String personalAccessToken = "accessToken";

Instance.Base_Instance.setInstance("https://{server:port}/tfs/");
var webApi = new AzDClientApi(organisation, personalAccessToken);

var core = webApi.getCoreApi();
core.getProjects();
```

If this still doesn't work, then you can use one of the `send` methods from [RestClient](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/utils/RestClient.java#L209) class that accepts `requestUrl` which you can actually use to call the REST Api. Then create an instance of [JsonMapper](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/helpers/JsonMapper.java) and deserialise the response. Hope this helps.

Documentation on how to use `RestClient` can be founder [here](https://azure-devops-java-sdk-docs.readthedocs.io/en/latest/docs/tutorial/).

[Java docs](https://hkarthik7.github.io/azd-docs/)

**Comment by yperraud** [comment]
Hi @hkarthik7. First of all, thank you for your work. This library is awesome!
The approach with the setInstance method works well. Unfortunately, this improvement is not present in the release 5.0.8.
Do you have any idea about the release date of the next version?

**Comment by hkarthik7** [comment]
Hello @yperraud, Next version will be a minor incremental release and should be released next week. Currently I'm packed with office work so couldn't contribute much. I've already pushed the changes that fixes the open issues. I will leave a comment here to let you know once there is a new version. Cheers.

**Comment by hkarthik7** [comment]
Hello @yperraud, New version `v5.0.9` is released now.
