### ISSUE TITLE
Git push does not work because JSON output does not match examples

### ISSUE THREAD

**Issue by jvnoije** [hkarthik7/azure-devops-java-sdk#61]
I had some problems with [git pushes create](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-7.1&tabs=HTTP) and found two problems that are close related. 

1. the JSON content is filled with 'null' values. This causes undefined errors at the rest API.
2. the 'item' in [commits](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-7.1&tabs=HTTP#gitcommitref) => [changes](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-7.1&tabs=HTTP#gitchange) => item is stated as a string, and that is also the type that is used in this library. However if you look al [the examples](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pushes/create?view=azure-devops-rest-7.1&tabs=HTTP#add-a-text-file) you see that the item contains a 'path' parameter, with corresponds with a 'GitItem' type.

Steps to reproduce
------------------

```java
GitRefUpdate gitRefUpdate = new GitRefUpdate();
gitRefUpdate.setName("refs/heads/test_branch");

ItemContent itemContent = new ItemContent();
itemContent.setContentType(ItemContentType.RAWTEXT);
itemContent.setContent("Content of the file");

GitChange gitChange = new GitChange();
gitChange.setChangeType(VersionControlChangeType.ADD);
gitChange.setItem("/test_file.txt");
gitChange.setNewContent(itemContent);

GitCommitRef gitCommitRef = new GitCommitRef();
gitCommitRef.setComment("Add new test file");
gitCommitRef.setChanges(Collections.singletonList(gitChange));

GitPush gitPush = new GitPush();
gitPush.setRefUpdates(Collections.singletonList(gitRefUpdate));
gitPush.setCommits(Collections.singletonList(gitCommitRef));

gitApi.createPush(repositoryName, gitPush);
```

The above example results in the following JSON:

```json
{
  "_links": null,
  "commits": [
    {
      "_links": null,
      "author": null,
      "changeCounts": null,
      "changes": [
        {
          "changeId": null,
          "changeType": "add",
          "item": "/test_file.txt",
          "newContent": {
            "content": "Content of the file",
            "contentType": "rawText"
          },
          "newContentTemplate": null,
          "originalPath": null,
          "sourceServerItem": null,
          "url": null
        }
      ],
      "comment": "Add new test file",
      "commentTruncated": false,
      "commitId": null,
      "committer": null,
      "parents": null,
      "push": null,
      "remoteUrl": null,
      "statuses": null,
      "url": null,
      "workItems": null
    }
  ],
  "date": null,
  "pushId": null,
  "pushedBy": null,
  "refUpdates": [
    {
      "locked": false,
      "isLocked": false,
      "name": "refs/heads/test_branch",
      "newObjectId": null,
      "oldObjectId": null,
      "repositoryId": null
    }
  ],
  "repository": null,
  "url": null
}
```

Expected behavior
-----------------

```none
The new file is added (assuming there is not already a file with this name)
```

Actual behavior
---------------

```none
Getting a non descriptive error message:
```
```json
{
    "$id": "1",
    "innerException": null,
    "message": "The body of the request contains invalid Json.\r\nParameter name: contentStream",
    "typeName": "Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer",
    "typeKey": "InvalidArgumentValueException",
    "errorCode": 0,
    "eventId": 0
}
```

## Information Checklist

Kindly make sure that you have added all the following information above and checkoff the required fields otherwise the
issue template will be treated as an incomplete report.

- [x] Bug Description Added
- [x] Reproduce Steps Added
- [x] Expected Behaviour Added
- [x] Actual Behaviour Added

**Comment by jvnoije** [comment]
I have some changes ready to push in order to fix these issues, I will create a pull request tomorrow

**Comment by hkarthik7** [comment]
Hiya @jvnoije, thanks for raising the PR. I will review and merge it.
