### ISSUE TITLE
[Feature] Missing Pull Request Statuses object

### ISSUE THREAD

**Issue by vcivitani** [hkarthik7/azure-devops-java-sdk#64]
Hi, first of all, thank you for your work, it's amazing!

Using this library, I have found that it's missing the Pull Request Statuses object (i.e. GitPullRequestStatus[es]), to get the status of a pull request's checks.

I refer to this: 
https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-statuses?view=azure-devops-rest-7.0

having this, would be possible to list the pull request statuses:
https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-statuses/list?view=azure-devops-rest-7.0&tabs=HTTP
or get a specific pull request status:
https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-statuses/get?view=azure-devops-rest-7.0&tabs=HTTP

And it would help to verify a pull request check.

One more time: thank you for your work!

**Comment by hkarthik7** [comment]
Hiya @vcivitani, thanks for your kind words. I will definitely add it in the next release. Apologies, caught up with work and couldn't contribute much to the library. This should be in next version release.

**Comment by hkarthik7** [comment]
Hello @vcivitani, Support for GitPullRequestStatus is released in `v5.0.9`.
