### ISSUE TITLE
[Improvement] Add more examples to GitApi.md

### ISSUE THREAD

**Issue by vcivitani** [hkarthik7/azure-devops-java-sdk#65]
Hi, first of all: thank you for your work! :)

Your library was helpful, same way as your examples.

When I started to use your library, it was helpful this example document:
https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/examples/GitApi.md

I detected some lack of examples. For example, some examples to do a simple case, as:

1. create new branch
2. get existing file, update its content and commit changes
3. create pull request from new branch to main branch

or
4. delete branch from point 2

it would be nice to have this kind of examples in the file.

as example:

// create branch
var git = webApi.getGitApi();
String newBranch = "branch_name";
String mainBranchId = git.getBranch(repositoryName, branchName).getObjectId();
String oldBranchId = "0000000000000000000000000000000000000000"; // Azure rules ¯\_(ツ)_/¯
GitRefUpdateResult gitRefUpdateResult = git.updateRef(repositoryName, "refs/heads/" + newBranchName, oldBranchId, mainBranchId);

// commit
GitPush gitPush = new GitPush();
gitPush.setCommits(gitCommitRefList);
gitPush.setRefUpdates(gitRefUpdateList);
git.createPush(repoId, gitPush);

// create pull request
GitPullRequest gitPullRequest = new GitPullRequest();
gitPullRequest.setDescription("PR test description");
gitPullRequest.setIsDraft(false);
gitPullRequest.setLabels(new ArrayList<>());
gitPullRequest.setReviewers(new ArrayList<>());
gitPullRequest.setSourceRefName("refs/heads/" + newBranch);
gitPullRequest.setTargetRefName("refs/heads/main");
gitPullRequest.setTitle("PR title");
gitPullRequest.setRepository(repository);
GitPullRequest gitPullRequestOutput = git.createPullRequest(gitPullRequest);

// delete branch
String deleteBranchId = "0000000000000000000000000000000000000000"; // Azure rules ¯\_(ツ)_/¯
String oldObjectId = git.getBranch(sepositoryName, branchToDeleteName).getObjectId();
gitRefUpdateResult = git.updateRef(repositoryName, "refs/heads/" + branchToDeleteName, oldObjectId, deleteBranchId);

**Comment by hkarthik7** [comment]
Hiya @vcivitani, thanks for your kind words. I will definitely add it in the next release and update the examples and documentation going forward. Cheers.
