### ISSUE TITLE
How to get the get the team capacity?

### ISSUE THREAD

**Issue by potito-coluccelli** [hkarthik7/azure-devops-java-sdk#66]
Hi, 
thanks for this great library.
I was trying to understand if there is a way to call the method to get the team capacity. I looked in the workApi but I didn't find anything.
Here is the link of the method I'm talking about.

https://learn.microsoft.com/en-us/rest/api/azure/devops/work/capacities/get-capacities-with-identity-ref-and-totals?view=azure-devops-rest-7.0#teamcapacity

**Comment by hkarthik7** [comment]
Hi @potito-coluccelli. thanks for the positive comments. I'm afraid `TeamCapacity` is not added in the library yet. I will add it in the next release.

For now you use [RestClient](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/utils/RestClient.java) class and call any Azure DevOps REST API and use the script [scrape.py](https://github.com/hkarthik7/azure-devops-java-sdk/tree/main/tools) under `tools` folder to create the `TeamCapacity` definition. 

[Here](https://azure-devops-java-sdk-docs.readthedocs.io/en/latest/docs/tutorial/) is the link that shows how to use [RestClient](https://github.com/hkarthik7/azure-devops-java-sdk/blob/main/azd/src/main/java/org/azd/utils/RestClient.java) class.

Or, you can create a PR and I will be more than happy to merge it 😄

**Comment by hkarthik7** [comment]
Hiya @potito-coluccelli, This is now released in `v5.0.9`.
