### ISSUE TITLE
[Improvement] Add ability for GitApi.getRepositories() to include hidden repositories

### ISSUE THREAD

**Issue by rudderfeet** [hkarthik7/azure-devops-java-sdk#68]
This is a wonderful library and I'm using it weekly to extract a bunch of interesting insights for my organization - thank you!

One thing I noticed about GitApi's getRepositories() method is that it doesn't allow one to set the **includeHidden** switch, which I believe is necessary to include Wiki repos in search results without calling getRepository(repoName) explicitly.  This means I have to perform a few more steps to search for Wikis, then iterate through each one to get the remote URLs for further cloning and analysis.  Someone else may also like to specify **includeAllUrls** and **includeLinks** as well, so I'm wondering if you could leave the existing getRepositories() method alone and add a convenience method that accepts those three switches?

Thank you in advance - this is a genuinely useful library! - Scott

**Comment by hkarthik7** [comment]
Hiya @rudderfeet, Thanks for the kind words, I’m glad that the library is useful. 
I will add it immediately and release it in next version.

**Comment by rudderfeet** [comment]
Thank you, I genuinely appreciate it!  As an aside it's been a while since I contributed to OSS, so my apologies for not submitting a PR.  I need to build that skill back, clearly :-).

**Comment by hkarthik7** [comment]
Hiya @rudderfeet, Apologies for releasing this late, I was bit caught up with work. Now the version `5.0.10` is released and added 3 overloaded methods `getRepositories()`, below are the method signatures. I will keep this issue open and monitor for sometime.

```java
Repositories getRepositories(boolean includeHidden) throws AzDException;

Repositories getRepositories(boolean includeLinks, boolean includeAllUrls) throws AzDException;

Repositories getRepositories(boolean includeAllUrls, boolean includeLinks, boolean includeHidden) throws AzDException;
```
