### ISSUE TITLE
queueBuild with parameters issue

### ISSUE THREAD

**Issue by MartinPriebe** [hkarthik7/azure-devops-java-sdk#7]
# Not able to trigger buildDefinition with buildParameters

Steps to reproduce
------------------

my definitionId is 162

queue build like in the example
`build.queueBuild(162);`
works

but with parameters not.

java sample code

```
var parameters = new HashMap<String, Object>();
BuildDefinition def = new BuildDefinition();
def.setId(162);
parameters.put("definition", def);
parameters.put("key1", "value1");
build.queueBuild(parameters);
```
 

Expected behavior
-----------------

build triggered with parameter

Actual behavior
---------------

Message

DefinitionNotFoundException: Build pipeline 162 was not found.

**Comment by MartinPriebe** [comment]
or would be the REST api "pipelines" a better option?
https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run-pipeline?view=azure-devops-rest-6.0&viewFallbackFrom=azure-devops-rest-7.1

**Comment by hkarthik7** [comment]
Hello @MartinPriebe let me take a look.

**Comment by MartinPriebe** [comment]
Ok, got it.
The issue was that I used the BuildDefinition object.
But this contains also revision id which was zero.

```
{
	"definition": {
		"_links": null,
		"authoredBy": null,
		"badgeEnabled": false,
		"buildNumberFormat": null,
		"comment": null,
		"createdDate": null,
		"demands": null,
		"description": null,
		"draftOf": null,
		"drafts": null,
		"dropLocation": null,
		"id": 162,
		"jobAuthorizationScope": null,
		"jobCancelTimeoutInMinutes": 0,
		"jobTimeoutInMinutes": 0,
		"latestBuild": null,
		"latestCompletedBuild": null,
		"metrics": null,
		"name": null,
		"options": null,
		"path": null,
		"process": null,
		"project": null,
		"properties": null,
		"quality": null,
		"queue": null,
		"queueStatus": null,
		"repository": null,
		"retentionRules": null,
		"revision": 0,
		"tags": null,
		"triggers": null,
		"type": null,
		"url": null,
		"uri": null,
		"variableGroups": null,
		"variables": null
	}
}
```

So now I create and use a smaller object .... and my parameters object was also wrong.
Here the final code which I use.


```
var body = new HashMap<String, Object>();

var definition = new HashMap<String, Object>();
definition.put("id", 162);
body.put("definition", definition);

var parameters = new HashMap<String, Object>();
parameters.put("key1", "value1");
parameters.put("key2", "value2");
JsonMapper mapper = new JsonMapper();
var str = mapper.writeValueAsString(parameters);
body.put("parameters", str);
```

**Comment by hkarthik7** [comment]
@MartinPriebe cheers, glad that worked and thanks for sharing.
