### ISSUE TITLE
GitPullRequest getCommits() is always null

### ISSUE THREAD

**Issue by razisam** [hkarthik7/azure-devops-java-sdk#71]
# Issue Template

When calling the git API, the `getCommits()` always returns null:

```
        AzDClientApi webApi = new AzDClientApi(Constants.ORGANIZATION_NAME, Constants.PROJECT_NAME, Constants.PERSONAL_ACCESS_TOKEN);
        GitApi git = webApi.getGitApi();
        PullRequests pullRequests = git.getPullRequests(Constants.REPO_NAME);
        List<GitPullRequest> gitPullRequests = pullRequests.getPullRequests();
        if (gitPullRequests == null) {
            return;
        }
        for (GitPullRequest gitPullRequest : gitPullRequests) {
            List<GitCommitRef> commits = gitPullRequest.getCommits();
// commits is always null

```

i tried with 5.0.10 and i also tried with 6.0.0-SNAPSHOT.

what am i doing wrong?

my goal is, to get all changed files from a pull request, to analyze the path of the files and add labels.

adding labels works fine:
`git.createPullRequestLabel(Constants.REPO_NAME, gitPullRequest.getPullRequestId(), "azd-tooling-test-feature-xyz");`

**Comment by hkarthik7** [comment]
Hello @razisam, I did try the [Get Pull Requests](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-requests?view=azure-devops-rest-7.1&tabs=HTTP) in postman, evern though the model is [GitPullRequest](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-requests?view=azure-devops-rest-7.1&tabs=HTTP#gitpullrequest) commits are not returned. Where as if you see the [Get Pull Request](https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-request?view=azure-devops-rest-7.1) Api, `includeCommits` flag is present to return the commits for a particular pull request. So, you should change your code as below. I've pushed these changes in new version `5.0.11`.

```java
        AzDClientApi webApi = new AzDClientApi(Constants.ORGANIZATION_NAME, 
            Constants.PROJECT_NAME, Constants.PERSONAL_ACCESS_TOKEN);

        GitApi git = webApi.getGitApi();

        PullRequests pullRequests = git.getPullRequests(Constants.REPO_NAME);

        List<GitPullRequest> gitPullRequests = pullRequests.getPullRequests();

        if (gitPullRequests == null) {
            return;
        }

        for (GitPullRequest gitPullRequest : gitPullRequests) {
            List<GitCommitRef> commits = git.getPullRequest(gitPullRequest.getRepository().getName(), 
                  gitPullRequest.getPullRequestId(), true).getCommits();
        }
```

**Comment by hkarthik7** [comment]
@razisam, Hope this is fixed, I'm closing the issue.
