### ISSUE TITLE
CVE "sonatype-2022-6438"

### ISSUE THREAD

**Issue by razisam** [hkarthik7/azure-devops-java-sdk#72]
Hello,

our sonar firewall is blocking your jars because of CVE "sonatype-2022-6438"

https://github.com/FasterXML/jackson-core/issues/861

can you please update jackson version.

thanks

**Comment by hkarthik7** [comment]
Hi @razisam, Thanks for raising this, I will update and push the new version within this week.

**Comment by hkarthik7** [comment]
Hi @razisam, This is now fixed in the new version `5.0.11`.

**Comment by hkarthik7** [comment]
@razisam, Hope this is fixed, I'm closing the issue.
